service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2 # asia pacific (Sydney)
  stage: dev

plugins:
  - serverless-offline

functions:
  helloworld:
    handler: src/helloworld.handler
